name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}} 🚧
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup PNPM ⚙️
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.3
      - name: Setup cache 💾
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies ⬇️
        run: pnpm i --frozen-lockfile
      - name: Build generator 🏗️
        working-directory: ./packages/generator
        run: pnpm build
      - name: Link globals 🖇️
        working-directory: ./packages/generator
        run: pnpm link . --global
      - name: Run Tests 🧪
        working-directory: ./packages/generator
        run: pnpm test
  Publish:
    runs-on: ubuntu-latest
    needs:
      - Test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}} 🚧
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup PNPM ⚙️
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.3
      - name: Setup cache 💾
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies ⬇️
        run: pnpm i --frozen-lockfile
      - name: Build generator 🏗️
        working-directory: ./packages/generator
        run: pnpm build
      - name: Publish 🗞️
        working-directory: ./packages/generator
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY_SKIP_INSTALL: 1
